version: '3'
services:
      mysql:
        image: mysql/mysql-server
        ports:
         - 8081:8081

      phpmyadmin :
        image:  phpmyadmin/phpmyadmin
        ports: 
         - 8080:80
        environment:
            PMA_HOST: "mysql"
            PMA_PORT: "8081"
        depends_on:
            - mysql