version: '3'
services:
      db:
        image: mysql/mysql-server

      phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
         - 8080:80
        environment:
          MYSQL_ROOT_PASSWORD: 123Admin
        depends_on:
            - db